<?php
/**
 * Project: edusogno-task
 * File: content.phtml
 * Author: wanpeninsula
 * Organization: Edusogno
 * Author URI: https://www.pennycodes.dev
 * Created: 11/10/2023 at 12:24 am
 *
 * Copyright (c) 2023 Edusogno. All rights reserved.
 */
global $app;
$token = !empty($_GET['token']) ? Utils::encode($_GET['token'], 'd') : '';

if (empty($token)) {
    Routes::redirect('events', 'admin');
}


$event  = $app->app('event');
$user  = $app->app('user');
$viewEvent = $event->getEvent($token);

if (empty($viewEvent)) {
    Routes::redirect('events', 'admin');
}
?>
<div class="pt-12 sm:pt-16">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
            <div class="sm:flex sm:items-center">
                <div class="sm:flex-auto">
                    <h1 class="text-xl font-semibold text-gray-900">Viewing Event</h1>
                </div>
                <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
                    <a  href="<?=Routes::loadAdminLink('events')?>" class="ml-3 inline-flex items-center rounded-md border border-transparent bg-brand px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-brand/80 focus:outline-none focus:ring-2 focus:ring-brand/80 focus:ring-offset-2">Back to Events</a>

                </div>
            </div>
        <div class="overflow-hidden bg-white mt-8 shadow sm:rounded-lg">
            <div class="px-4 py-5 sm:px-6">
                <h3 class="text-lg font-medium leading-6 text-gray-900">Event Details</h3>
                <p class="mt-1 max-w-2xl text-sm text-gray-500">Find the event details below.</p>
            </div>
            <div class="border-t border-gray-200">
                <dl>
                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">Event ID</dt>
                        <dd class="mt-1 font-bold text-sm text-gray-900 sm:col-span-2 sm:mt-0"><?=Utils::encode($viewEvent['id'], 'd') ?></dd>
                    </div>
                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">Event name</dt>
                        <dd class="mt-1 font-bold text-sm text-gray-900 sm:col-span-2 sm:mt-0"><?=$viewEvent['name'] ?></dd>
                    </div>
                    <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">Event Date</dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><?=date_create($viewEvent['date'])->format('D, d M Y \a\t H:i A') ?></dd>
                    </div>
                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">Attendees</dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <ul role="list" class="divide-y divide-gray-200 rounded-md border border-gray-200">
                                <?php
                                if (count($viewEvent['attendees']) > 0) {
                                    foreach ($viewEvent['attendees'] as $attendee ):
                                        $userInfo = $user->fetchUser($attendee);
                                    ?>
                                        <li class="flex items-center justify-between py-3 pl-3 pr-4 text-sm">
                                            <div class="flex w-0 flex-1 items-center">
                                                <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M15.621 4.379a3 3 0 00-4.242 0l-7 7a3 3 0 004.241 4.243h.001l.497-.5a.75.75 0 011.064 1.057l-.498.501-.002.002a4.5 4.5 0 01-6.364-6.364l7-7a4.5 4.5 0 016.368 6.36l-3.455 3.553A2.625 2.625 0 119.52 9.52l3.45-3.451a.75.75 0 111.061 1.06l-3.45 3.451a1.125 1.125 0 001.587 1.595l3.454-3.553a3 3 0 000-4.242z" clip-rule="evenodd" />
                                                </svg>
                                                <span class="ml-2 w-0 flex-1"><?=$userInfo['name']?></span>
                                            </div>
                                        </li>

                                        <?php
                                    endforeach;
                                }
                                else {
                                    ?>
                                    <li class="flex items-center justify-between py-3 pl-3 pr-4 text-sm">
                                        <span class="ml-2 w-0 flex-1">
                                            There are no attendees for this event.
                                        </span>
                                    </li>
                                <?php
                                }
                                ?>
                            </ul>
                        </dd>
                    </div>
                </dl>
            </div>
        </div>
        </div>


</div>

