<?php
/**
 * Project: edusogno-task
 * File: content.phtml
 * Author: wanpeninsula
 * Organization: Edusogno
 * Author URI: https://www.pennycodes.dev
 * Created: 10/10/2023 at 11:47 pm
 *
 * Copyright (c) 2023 Edusogno. All rights reserved.
 */

global $app;
$token = !empty($_GET['token']) ? Utils::encode($_GET['token'], 'd') : '';

if (empty($token)) {
    Routes::redirect('events', 'admin');
}


$event  = $app->app('event');
$user  = $app->app('user');
$editEvent = $event->getEvent($token);

if (empty($editEvent)) {
    Routes::redirect('events', 'admin');
}
$users = $user->allUsers();

?>
<div class="pt-12 sm:pt-16">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
        <div class="">
            <div class="sm:flex sm:items-center">
                <div class="sm:flex-auto">
                    <h1 class="text-xl font-semibold text-gray-900">Editing Event <?=$editEvent['name'] ?></h1>
                </div>
                <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
                    <a  href="<?=Routes::loadAdminLink('events')?>" class="ml-3 inline-flex items-center rounded-md border border-transparent bg-brand px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-brand/80 focus:outline-none focus:ring-2 focus:ring-brand/80 focus:ring-offset-2">Back to Events</a>

                </div>
            </div>
            <div class="lg:grid lg:grid-cols-12 place-content-center mt-8 lg:gap-x-5">
                <div class="space-y-6 sm:px-6 lg:col-span-12 lg:px-0">
                    <form id="eventForm">
                        <div class="shadow sm:overflow-hidden sm:rounded-md  border border-brand-secondary">
                            <div class="space-y-6 bg-white py-6 px-4 sm:p-6">
                                <div>
                                    <h3 class="text-lg font-medium leading-6 text-gray-900">Event Information</h3>
                                    <p class="mt-1 text-sm text-gray-500">Fill out the form below to create an event.</p>
                                </div>

                                <div class="grid grid-cols-6 gap-6">
                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="event-name" class="block text-sm font-medium text-gray-700">Event name</label>
                                        <input type="text" name="name" id="event-name"
                                               placeholder="Event Name"
                                               required
                                               value="<?=$editEvent['name'] ?>"
                                               class="block w-full appearance-none text-brand-dark ring-0 border-0 border-b-2 border-brand-secondary px-3 py-2 placeholder-brand-placeholder shadow-sm focus:border-0 focus:border-b-2 focus:border-brand focus:outline-none focus:ring-0 sm:text-sm">
                                    </div>
                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="event-date" class="block text-sm font-medium text-gray-700">Event Date</label>
                                        <input type="datetime-local" name="date" id="event-date"
                                               placeholder="Event Name"
                                               value="<?=$editEvent['date'] ?>"
                                               class="block w-full appearance-none text-brand-dark ring-0 border-0 border-b-2 border-brand-secondary px-3 py-2 placeholder-brand-placeholder shadow-sm focus:border-0 focus:border-b-2 focus:border-brand focus:outline-none focus:ring-0 sm:text-sm">
                                    </div>


                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="attendees" class="block text-sm font-medium text-gray-700">Add Attendees (optional)</label>
                                        <select id="attendees" name="attendees[]" multiple
                                                class="block w-full appearance-none text-brand-dark ring-0 border-0 border-b-2 border-brand-secondary px-3 py-2 placeholder-brand-placeholder shadow-sm focus:border-0 focus:border-b-2 focus:border-brand focus:outline-none focus:ring-0 sm:text-sm">
                                            <option value="">Select Attendees</option>
                                            <?php
                                            if (count($users) > 0) {
                                                foreach ($users as $user) {
                                                    $selected = in_array($user['id'], $editEvent['attendees']) ? 'selected' : '';
                                                    ?>
                                                    <option <?=$selected?> value="<?=$user['id']?>"><?=$user['name']?></option>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </select>
                                        <small class="text-gray-500">Hold down the Ctrl (windows) / Command (Mac) button to select multiple options.</small>
                                    </div>

                                    <input type="hidden" name="hash_id" value="<?=Session::createFormToken()?>">
                                    <input type="hidden" name="token" value="<?=$editEvent['id']?>">
                                </div>
                            </div>
                            <div class="bg-gray-50 px-4 py-3 text-right sm:px-6">
                                <button type="submit"
                                        class="inline-flex justify-center  btn-submit rounded-md border border-transparent bg-brand py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-brand/70 focus:outline-none focus:ring-2 focus:ring-brand focus:ring-offset-2">Update Event</button>
                                <button type="button" class="inline-flex btn-loading hidden justify-center items-center px-4 py-2 font-semibold leading-6 text-sm shadow rounded-md text-white bg-brand hover:bg-brand/70 transition ease-in-out duration-150 cursor-not-allowed" disabled="">
                                    <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                                        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                    </svg>
                                    Loading...
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>


<script>

    document.querySelector('#eventForm').addEventListener('submit', (e) => {
        e.preventDefault();
        eventForm();
    });


    const btnSubmit = document.querySelector('.btn-submit');
    const btnLoading = document.querySelector('.btn-loading');

    const eventForm = () => {
        const form = document.querySelector('#eventForm');

        const url = Ed_Ajax_Requests_File() + '?f=event&s=update';

        const formData = new FormData(form);

        const xhr = new XMLHttpRequest();
        xhr.open("POST", url);
        xhr.responseType = "json";
        xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");

        // Disable submit button and show loading indicator
        btnSubmit.classList.add('hidden');
        btnLoading.classList.remove('hidden');

        xhr.onreadystatechange = function(data) {
            if (xhr.readyState === XMLHttpRequest.DONE) {
                const response = data.target.response;
                if (xhr.status === 200) {
                    notyf.success(response.message);
                    form.reset();
                    setTimeout(() => window.location.assign(Ed_Admin_Url() + "/events"), 1000);
                } else {
                    if (xhr.status === 0) {
                        notyf.error('Connection timed out. Check your network connectivity and retry');
                    } else {
                        notyf.error(response?.message || "An error occurred and that is all we know");
                    }
                }

                // Re-enable submit button and hide loading indicator
                btnSubmit.classList.remove('hidden');
                btnLoading.classList.add('hidden');
            }
        };

        xhr.send(formData);

    }
</script>
