<?php
/**
 * Project: edusogno-task
 * File: header.phtml
 * Author: wanpeninsula
 * Organization: Edusogno
 * Author URI: https://www.pennycodes.dev
 * Created: 09/10/2023 at 9:16 pm
 *
 * Copyright (c) 2023 Edusogno. All rights reserved.
 */

?>

<nav class="bg-light sticky top-0 z-30 h-24 rounded-b-lg drop-shadow shadow shadow-brand">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div class="relative flex h-24 justify-between">
            <div class="flex flex-1">
                <div class="flex flex-shrink-0 items-center">
                    <a
                            href="<?=Routes::loadSiteLink()?>"
                    >
                    <img class="h-auto w-auto" src="<?=Routes::loadPublicAssets('assets/brand/logo.png')?>" alt="<?=EdusognoApp::config('site_name')?>">
                    </a>
                </div>
            </div>
            <?php
            if (Session::isUser()) {
                ?>
            <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">

                <div class="relative ml-3">
                    <div>
                        <button type="button" class="flex rounded-full bg-white text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                            <span class="sr-only">Open user menu</span>

                            <span class="inline-flex h-10 w-10 items-center justify-center rounded-full bg-brand">
                              <span class="font-medium leading-none text-white"><?=EdusognoApp::user()['user']['initials'] ?></span>
                            </span>
                        </button>
                    </div>

                    <div class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none scale-0 opacity-0" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1" id="user-menu-dropdown">
                        <a href="<?=Routes::loadSiteLink('logout/'. EdusognoApp::user()['token'])?>" class="block px-4 py-2 text-sm text-gray-700 hover:text-brand" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>
                    </div>
                </div>
            </div>
            <?php
            }
            ?>
        </div>
    </div>

</nav>
