<?php
/**
 * Project: edusogno-task
 * File: content.phtml
 * Author: wanpeninsula
 * Organization: Edusogno
 * Author URI: https://www.pennycodes.dev
 * Created: 10/10/2023 at 10:20 pm
 *
 * Copyright (c) 2023 Edusogno. All rights reserved.
 */
global $app;

$admin = EdusognoApp::admin()['admin'];
$user  = $app->app('user');
$event  = $app->app('event');


?>

<div class="pt-12 sm:pt-16">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
        <div class="mx-auto max-w-4xl text-center">
            <h2 class="text-3xl font-bold tracking-tight text-brand-secondary sm:text-4xl"> Hi <?=$admin['first_name']?>, welcome</h2>
            <p class="mt-3 text-xl text-gray-500 sm:mt-4">
                A summary of system activities
            </p>
        </div>
    </div>
    <div class="mt-10 pb-12 sm:pb-16">
        <div class="relative">
            <div class="absolute inset-0 h-1/2"></div>
            <div class="relative mx-auto max-w-7xl px-6 lg:px-8">
                <div class="mx-auto max-w-4xl">
                    <dl class="rounded-lg bg-white shadow-lg sm:grid sm:grid-cols-2">
                        <div class="flex flex-col border-b border-gray-100 p-6 text-center sm:border-0 sm:border-r">
                            <dt class="order-2 mt-2 text-lg font-medium leading-6 text-gray-500">Total Users</dt>
                            <dd class="order-1 text-5xl font-bold tracking-tight text-brand"><?=$user->totalUsers()?></dd>
                        </div>
                        <div class="flex flex-col border-t border-b border-gray-100 p-6 text-center sm:border-0 sm:border-l sm:border-r">
                            <dt class="order-2 mt-2 text-lg font-medium leading-6 text-gray-500">Total Events</dt>
                            <dd class="order-1 text-5xl font-bold tracking-tight text-brand"><?=$event->totalEvents()?></dd>
                        </div>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>





